M48
; DRILL file {KiCad 9.0.1-rc2} date 2025-11-09T14:34:19-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-09T14:34:19-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-rc2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X83.0Y-22.5
X99.0Y-22.5
T2
X30.0Y-32.0
X30.0Y-183.0
X152.0Y-32.0
X152.0Y-183.0
M30
