M48
; DRILL file {KiCad 9.0.1-rc2} date 2025-03-29T14:31:01-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-29T14:31:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-rc2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X88.0Y-53.5
X178.5Y-142.0
T2
X84.5Y-54.5
X84.5Y-88.5
X84.5Y-145.5
X179.5Y-54.5
X179.5Y-88.5
X179.5Y-145.5
M30
