M48
; DRILL file {KiCad 9.0.1-rc2} date 2025-11-09T15:09:06-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-09T15:09:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-rc2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X46.2Y-96.11
X46.2Y-101.89
X119.774Y-96.072
X119.774Y-101.852
T2
X42.0Y-114.1
X121.35Y-86.85
T3
X115.25Y-111.4
X122.25Y-111.4
T4
X43.0Y-89.5
X123.0Y-89.5
M30
